apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: test-selfsigned
spec:
  secretName: test-selfsigned-secret
  dnsNames:
  - springboot-http2.hung.org.hk
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
