version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
    - "9200"
    - "9300"
    environment:
    - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports: 
    - "5601"

