version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
    - "9200"
    - "9300"
    environment:
    - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports: 
    - "5601:5601"
    
  nginx:
    image: nginx:1.18-alpine
    ports:
    - "9080:80"
    #- "9443:443"
    labels:
    - "co.elastic.logs/enabled=true"
    - "co.elastic.logs/module=nginx"
    restart: always
  
  #portainer:
  #  image: portainer/portainer-ce
  #  ports:
  #  - "9000:9000"
  #  volumes:
  #  - portainer_data:/data
  #  - "/var/run/docker.sock:/var/run/docker.sock"
  #  restart: always
      
volumes:
  portainer_data:

