version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    ports:
    - "9200"
    - "9300"
    environment:
    - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    restart: always
    ports: 
    - "5601:5601"
    
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    restart: always
    ports:
    - "9600:9600"
    - "5044:5044"
    #volumes:
    #- "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    
  nginx:
    image: nginx:1.18-alpine
    restart: always
    ports:
    - "9080:80"
    #- "9443:443"
    labels:
    - "co.elastic.logs/enabled=true"
    - "co.elastic.logs/module=nginx"
    - "co.elastic.logs/fileset.stdout=access"
    - "co.elastic.logs/fileset.stderr=error"

  springboot_webapp:
    image: kwonghung/springboot-to-skaffold:latest
    restart: always
    labels:
    - "co.elastic.logs/enabled=true"
    - "co.elastic.logs/multiline.pattern=^[0-9]{4}-[0-9]{2}-[0-9]{2}"
    - "co.elastic.logs/multiline.negate=true"
    - "co.elastic.logs/multiline.match=after"

  #portainer:
  #  image: portainer/portainer-ce
  #  ports:
  #  - "9000:9000"
  #  volumes:
  #  - portainer_data:/data
  #  - "/var/run/docker.sock:/var/run/docker.sock"
  #  restart: always
      
volumes:
  portainer_data:

