filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - config:
      - type: container
        paths:
        - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
- add_cloud_metadata: ~

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'

output.logstash:
  hosts: ["logstash:5044"]
