logging.level: info

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
  - type: docker
    hints.enabled: true
    hints.default_config.enabled: false
    templates:
    - conditions:
        contains:
          docker.container.name: "springboot"
      config:
        field:
          log_type: "springboot-app-log"
    - conditions:
        contains:
          docker.container.name: "nginx"
      config:
        field:
          log_type: "nginx-access-log"
      

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.ilm:
  enabled: false
  #rollover_alias: "filebeat-%{[event.module]}-%{[event.type]}"
  #overwrite: true

setup.template:
  name: 'filebeat3'
  pattern: 'filebeat3-*'

#output.console:
#  pretty: true

output.elasticsearch:
  #index: 'filebeat-%{[event.module]}-%{[event.type]}-%{+yyyy.MM.dd}'
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  indices:
  - index: "filebeat-nginx-access-%{+yyyy.MM.dd}"
    when.and:
    - equals:
        event.module: nginx
    - equals:
        event.type: access
  - index: "filebeat-nginx-error-%{+yyyy.MM.dd}"
    when.and:
    - equals:
        event.module: nginx
    - equals:
        event.type: error
