logging.level: debug

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
- module: nginx
  access:
    enabled: true
  error:
    enabled: false
  ingress_controller:
    enabled: false

filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.name: nginx
      config:
      - module: nginx
        access:
          enabled: true
          var.paths: ["/var/lib/docker/containers/${data.docker.container.id}/*.log"]
        error:
          enabled: true
          var.paths: ["/var/lib/docker/containers/${data.docker.container.id}/*.log"]
        ingress_controller:
          enabled: false

    #hints.enabled: true
    #hints.default_config.enabled: false
    #templates:
    #- config:
    #  - type: container
    #    paths:
    #    - /var/lib/docker/containers/${data.docker.container.id}/*.log
    #multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    #multiline.negate: true
    #multiline.match: after

processors:
- add_cloud_metadata: ~

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'

output.logstash:
  hosts: ["logstash:5044"]
