apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    ver: "7.10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
      ver: "7.10"
  template:
    metadata:
      labels:
        app: elasticsearch
        ver: "7.10"
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        ports:
        - name: http
          containerPort: 9200
---
