apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: default
spec:
  ca:
    secretName: my-ca-keypair
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tomcat-cert
  namespace: default
spec:
  secretName: tomcat-secret
  dnsNames:
  - tomcat-http2.hung.org.hk
  issuerRef:
    name: my-ca-issuer
    kind: Issuer    
