apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: default
spec:
  ca:
    secretName: my-ca-keypair
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tomcat-cert
  namespace: default
spec:
  secretName: tomcat-secret
  duration: 120h
  renewBefore: 24h
  organization:
  - Funny Firm
  dnsNames:
  - tomcat-http2.hung.org.hk
  - hello.com
  issuerRef:
    name: my-ca-issuer
    kind: Issuer    
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tomcat-ingress-cert
  namespace: default
spec:
  secretName: tomcat-ingress-secret
  subject:
    countries:
    - HK
    provinces:
    - Hong Kong
    organizationalUnits:
    - Fun Fund Fair
  usages:
  - digital signature
  - key encipherment
  dnsNames:
  - tomcat-http2.hung.org.hk
  issuerRef:
    name: my-ca-issuer
    kind: Issuer    
