apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tomcat-http2
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 80
      protocol: HTTP
    hosts:
    - *.hung.org.hk
  - port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: tomcat-secret
    hosts:
    - *.hung.org.hk
