apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: istio-system
spec:
  ca:
    secretName: my-root-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tomcat-cert
  namespace: istio-system
spec:
  secretName: tomcat-secret
  duration: 120h
  renewBefore: 24h
  isCA: false
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  organization:
  - Funny Firm
  dnsNames:
  - tomcat-http2.hung.org.hk
  - hello.com
  issuerRef:
    name: my-ca-issuer
    kind: Issuer  
