apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-http2
  labels:
    app: tomcat-http2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-http2
  template:
    metadata:
      labels:
        app: tomcat-http2
    spec:
      containers:
      - name: springboot
        image: kwonghung/spring-tomcat-http2:latest
        ports:
        - containerPort: 8080
        env:
        - name: spring_profiles_active
          value: "k8s"
        volumeMounts:
        - name: keystore
          mountPath: /usr/local/springboot/keystore 
      initContainers:
      - name: openssl
        image: frapsoft/openssl:latest
        workingDir: /usr/local/certs/tls
        args:
        - pkcs12 
        - "-export"
        - "-out"
        - /usr/local/certs/keystore/keystore.p12
        - "-passout"
        - "pass:abcd1234"
        - "-inkey"
        - /usr/local/certs/tls/tls.key 
        - "-name"
        - tomcat 
        - "-in"
        - /usr/local/certs/tls/tls.crt
        - "-CAfile"
        - /usr/local/certs/tls/ca.crt
        volumeMounts:
        - name: keystore
          mountPath: /usr/local/certs/keystore
        - name: tls-secret
          mountPath: /usr/local/certs/tls
      volumes:
      - name: keystore
        emptyDir: {}
      - name: tls-secret
        secret:
          secretName: tomcat-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-http2
  labels:
    app: tomcat-http2
spec:
  selector:
    app: tomcat-http2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spring-http2-ingress
spec:
  tls:
  - hosts:
    - tomcat-http2.hung.org.hk
    secretName: tomcat-ingress-secret
  rules:
  - host: tomcat-http2.hung.org.hk
    http:
      paths:
      - backend:
          serviceName: springboot-http2
          servicePort: http
