apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1.17-deploy
  labels:
    app: nginx-v1.17-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: v1.17
  template:
    metadata:
      labels:
        app: nginx
        version: v1.17
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1.16-deploy
  labels:
    app: nginx-v1.16-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: v1.16
  template:
    metadata:
      labels:
        app: nginx
        version: v1.16
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
spec:
  hosts:
  - nginx.default.svc.cluster.local
  http:
  - route:
    - destination:
        host: nginx
        subset: v117
    - destination:
        host: nginx
        subset: v116
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-dest-rule
spec:
  host: nginx.default.svc.cluster.local
  subsets:
  - name: v117
    labels:
      version: v1.17
  - name: v116
    labels:
      version: v1.16
