apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static-files
  namespace: default
data:
  echo.txt: |-
    text="Hello!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v117
  labels:
    deploy: nginx
    version: "1.17"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: 1.17
  template:
    metadata:
      labels:
        app: nginx
        version: 1.17
        minor-version: 1.17.9
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.9
        ports:
        - containerPort: 80
        - containerPort: 443
