apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1.17-deploy
  labels:
    app: nginx-1.17-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1.17
  template:
    metadata:
      labels:
        app: nginx-1.17
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1.16-deploy
  labels:
    app: nginx-1.16-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-1.16
  template:
    metadata:
      labels:
        app: nginx-1.16
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx117svc
spec:
  selector:
    app: nginx-1.17-deploy
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx116svc
spec:
  selector:
    app: nginx-1.16-deploy
  ports:
  - protocol: TCP
    port: 80
