apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-v9-deploy
  labels:
    deploy: tomcat
    version: v9
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: tomcat
      version: v9
  template:
    metadata:
      labels:
        pod: tomcat
        version: v9
        server: app-server
        jdk: openjdk-11
    spec:
      containers:
      - name: tomcat
        image: tomcat:9
        ports:
        - containerPort: 8080
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-v9-svc
  labels:
    service: tomcat
    version: v9
spec:
  selector:
    pod: tomcat
    version: v9
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-v8.5-deploy
  labels:
    app: tomcat-v8.5-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: tomcat
      version: v8.5
  template:
    metadata:
      labels:
        pod: tomcat
        version: v8.5
        server: app-server
        jdk: openjdk-11
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5
        ports:
        - containerPort: 8080
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-v8.5-svc
  labels:
    service: tomcat
    version: v8.5
spec:
  selector:
    pod: tomcat
    version: v8.5
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
